//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Please_Dont_Fail_Me_Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Please_Dont_Fail_Me_Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼
        ///███▀▀▀██┼███▀▀▀███┼███▀█▄█▀███┼██▀▀▀
        ///██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼█┼┼┼██┼██┼┼┼
        ///██┼┼┼▄▄▄┼██▄▄▄▄▄██┼██┼┼┼▀┼┼┼██┼██▀▀▀
        ///██┼┼┼┼██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██┼┼┼
        ///███▄▄▄██┼██┼┼┼┼┼██┼██┼┼┼┼┼┼┼██┼██▄▄▄
        ///┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼
        ///███▀▀▀███┼▀███┼┼██▀┼██▀▀▀┼██▀▀▀▀██▄┼
        ///██┼┼┼┼┼██┼┼┼██┼┼██┼┼██┼┼┼┼██┼┼┼┼┼██┼
        ///██┼┼┼┼┼██┼┼┼██┼┼██┼┼██▀▀▀┼██▄▄▄▄▄▀▀┼
        ///██┼┼┼┼┼██┼┼┼██┼┼█▀┼┼██┼┼┼┼██┼┼┼┼┼██┼
        ///███▄▄▄███┼┼┼─▀█▀┼┼─┼██▄▄▄┼██┼┼┼┼┼██▄
        ///┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼┼.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═══════════════════════╗
        ///║       Inventory       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///╚═══════════════════════╝.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █████████████████████████
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░█░░░░░░░░░█
        ///█████░░░░░░░░░███████████
        ///█░░░░░░░░░░░░░███████████
        ///█░░░░░░░░░░░░░███████████
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█████░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█████████████████████████.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═══════════════════════╗
        ///║       Inventory       ║
        ///║                       ║
        ///║                       ║
        ///║  You got a new item!  ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///║                       ║
        ///╚═══════════════════════╝.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪╪█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█░░░░░░░░░████░░░░░░░░░░█
        ///█╪╪╪╪╪╪╪╪╪████╪╪╪╪╪╪╪╪╪╪█.
        /// </summary>
        internal static string Outside {
            get {
                return ResourceManager.GetString("Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █████████████████████████
        ///█░░░░░░░██░░░░░░░░░░░░░░█
        ///█████░░░██░░░░░░░░░░░░░░█
        ///█████░░░░░░░░░███████████
        ///█████░░░░░░░░░███████████
        ///█████░░░░░░░░░███████████
        ///█████░░░░░░░░░░░░░░░░░░░█
        ///█████░░░██░░░░░░██░░░░░░█
        ///█████░░░██░░░░░░██░░░░░░█
        ///█████░░░██░░░░░░██░░░░░░█
        ///█████░░░██░░░░░░██░░░░░░█
        ///█████░░░██████████░░░░░░█
        ///█████████████████████████.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █████████████████████████
        ///████████░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░└░░░░└░░░░└░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░└░░░░└░░░░└░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░└░░░░└░░░░└░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█░░░░└░░░░└░░░░└░░░░░░░░█
        ///█░░░░░░░░░░░░░░░░░░░░░░░█
        ///█████████████████████████.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
    }
}
